### PR TITLE
Fix installation.txt

### PR DESCRIPTION
**Pull request by akovalyov**
Add a note about how to reload .bashrc without need to log out\log in

### CODE REVIEW

**Comment by timthelion** [comment]
Does this work for all terminals, or only the current one?

**Comment by akovalyov** [comment]
@timthelion it won't work for terminals which were opened before the command except the one in which the command is launched. For new terminal windows everything will be fine.

**Comment by timthelion** [comment]
I appreciate the patch and I agree that it is a cool tip. However, I'm worried that users would be confused by the edge cases. I feel that logging out and back in again is very reliable and the effort of doing so does not justify a potential cause of confusion.

**Comment by timthelion** [comment]
Thankyou for contributing.

**Pull request closed without merging**
